### ISSUE TITLE
Kernel Panic 

### ISSUE THREAD

**Issue by NeverBeenBasic** [REMnux/website-source#1]
Hello, I am using a windows 11 computer and keep getting a kernel panic message when starting the REMNux OVA in VirtualBox. Can someone assist me and troubleshoot me through this? 

![remnux kernel failure](https://user-images.githubusercontent.com/108370810/215269985-09e6f381-df27-416e-b148-90b61155b79a.png)

**Comment by lennyzeltser** [comment]
Sorry, there are too many possibilities for me to be able to assist. My recommendation, if you're unable to resolve this, is to start by installing a brand new Ubuntu 20.04 virtual machine and then add REMnux to it. See the i[nstalling from scratch instructions](https://docs.remnux.org/install-distro/install-from-scratch).
